Feature1- new locators
SvitlanaGuba/new-project1 pull request #1
Opened 2024-05-06 16:05 UTC by SvitlanaGuba

Added locators - commands folder: all html files

2024-05-07 19:22 UTC, SanitarskyiDmytro requested changes
Беспосередньо завдання з домашки зроблено правильно. Є коментарі тільки до зайвих файлів в проекті і до пустих рядків )

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on scripts/start.js
> +
зайвий пустий рядок треба видалити)

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on .idea/.gitignore
Додайте всю папку .idea включно з цим файлом у .gitignore що знаходиться в корні проекту

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on .idea/g2-cypress-sandbox.iml
Додайте всю папку .idea включно з цим файлом у .gitignore що знаходиться в корні проекту

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on .idea/misc.xml
Додайте всю папку .idea включно з цим файлом у .gitignore що знаходиться в корні проекту

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on .idea/modules.xml
Додайте всю папку .idea включно з цим файлом у .gitignore що знаходиться в корні проекту

2024-05-07 19:22 UTC, SanitarskyiDmytro commented on .idea/vcs.xml
Додайте всю папку .idea включно з цим файлом у .gitignore що знаходиться в корні проекту

2024-05-07 21:45 UTC, SvitlanaGuba commented on scripts/start.js
> +
Виправлено, видалений пустий рядок між if

2024-05-07 22:12 UTC, SvitlanaGuba commented on .idea/.gitignore
Виправлено

2024-05-07 22:12 UTC, SvitlanaGuba commented on .idea/g2-cypress-sandbox.iml
Виправлено

2024-05-07 22:12 UTC, SvitlanaGuba commented on .idea/misc.xml
Виправлено

2024-05-07 22:13 UTC, SvitlanaGuba commented on .idea/modules.xml
Виправлено

2024-05-07 22:13 UTC, SvitlanaGuba commented on .idea/vcs.xml
Виправлено

2024-05-13 08:47 UTC, SanitarskyiDmytro approved these changes

2024-05-14 09:29 UTC, merged